name = "iog/aiken_halo2"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'iog/aiken_halo2'"

[repository]
user = "iog"
project = "aiken_halo2"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2"
source = "github"

[config.default]
network_id = 1
