name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aiken-lang/setup-aiken@v1
        with:
          version: v1.1.19
      - run: cargo run --example equations_test
      - run: cargo run --example atms_with_lookups
      - run: cd aiken-verifier/aiken_halo2 && aiken check
      - run: cd aiken-verifier/aiken_halo2 && aiken build
      - run: cargo run --example atms_with_lookups gwc_kzg
      - run: cd aiken-verifier/aiken_halo2 && aiken check
